Add GPGST NMEA message in ROS2 branch.
ros-drivers/nmea_msgs pull request #18
Opened 2022-11-25 09:49 UTC by nchleq

ROS2 message for GST NMEA sentences.
See: #17

2023-01-18 20:56 UTC, JWhitleyWork approved these changes
LGTM

2023-01-18 20:56 UTC, JWhitleyWork commented
Calling @evenator for review and merge.

2023-01-18 22:27 UTC, evenator requested changes
LGTM aside from a small request to keep the files in the CMakeLists.txt file in order.

2023-01-18 22:27 UTC, evenator commented on CMakeLists.txt
>     "msg/Gpgsa.msg"
To maintain alphabetical order:
```suggestion
   "msg/Gpgsa.msg"
   "msg/Gpgst.msg"
```

2023-01-23 09:35 UTC, evenator approved these changes
LGTM

Thanks for the contribution!

2023-01-23 09:37 UTC, merged